### ISSUE TITLE
How to run a JSON output?

### ISSUE THREAD

**Issue by nurzaman7** [conversational-interfaces/dms-compiler#11]
After the compilation, how to further run JSON output such as-
{
  "@do": [
    { "@act": "`Guess the number!`" },
    { "@act": "`Please input your guess.`" },
    {
      "@fork": [{ "@do": [{ "@act": ["+", "`You guessed `", "_nlu"] }] }],
      "await": ["input"]
    }
  ]

**Comment by BinRoot** [comment]
Hi, thank you for your interest. Great question!

To run the JSON generated by the dms-compiler, you'll need a DMPL runtime. 

A working example of the DMPL runtime in JavaScript is demonstrated here: https://github.com/conversational-interfaces/dms-scratchpad

Specifically, the runtime is [dm.js](https://github.com/conversational-interfaces/dms-scratchpad/tree/master/js), which is used by [worker.js](https://github.com/conversational-interfaces/dms-scratchpad/blob/master/js/worker.js#L21).

**Comment by nurzaman7** [comment]
Thanks..! I am closing this issue.
