### ISSUE TITLE
Help with getting started

### ISSUE THREAD

**Issue by cjneely10** [conversational-interfaces/dms-compiler#5]
Good morning/afternoon,

Very interesting concept, I am curious to learn more. 

I apologize if my following question has an obvious solution that I missed. After cloning this repository, moving into its directory, and running `yarn`, does a folder named `bin` automatically generate?

Currently, after I run yarn (and get 3 warnings), a `node_modules` directory is created. This directory does contain an inner directory named `.bin`, but the `.bin` directory does not contain the file `compile`.

Thank you for your assistance. Happy Holidays!

**Comment by BinRoot** [comment]
You're absolutely right, I forgot to include `bin/compile`. Latest [commit](https://github.com/conversational-interfaces/dms-compiler/commit/ba113c5120bf53fa504115a7620679b2cdd97830) fixes this issue.
